# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev
  workflow_dispatch:
    inputs:
      config:
        type: 'nothing'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clone dependencies
      run: |
        bash ./build_env.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true

    - name: Build
      run: |
        export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
        go env -w GO111MODULE=on
        go env -w GOPROXY=https://goproxy.cn,direct
        make clean && make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: estrace
        path: bin/estrace

